ticket:
  catalog-flight-uri: "http://ticket-service"
spring:
  r2dbc:
    url: r2dbc:postgresql://airline-postgres/airlinedb_booking
    username: user
    password: password
  flyway:
    url: jdbc:postgresql://airline-postgres/airlinedb_booking
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:9005/api/auth/.well-known/jwks.json
